### ISSUE TITLE
No matching autocommands upon searching

### ISSUE THREAD

**Issue by GergelyKalmar** [qxxxb/vim-searchhi#9] opened 2020-08-25 10:11 UTC
I'm getting a 'No matching autocommands' message every time after hitting enter on a search term, i.e. doing ``/search<enter>``. I'm not using ``vim-anzu`` or ``vim-asterisk``. Can I somehow figure it out where does this message come from?

**Comment by GergelyKalmar** [comment] 2020-08-25 11:22
It seems that the message disappears with ``vim-anzu`` installed, nevertheless, it would be great to get rid of it when ``vim-anzu`` is not installed.

**Comment by roachsinai** [comment] 2020-10-13 12:26
Same issue and no shows of matches count.

**Comment by qxxxb** [comment] 2020-10-13 19:12
Thanks for the report and sorry for the late response. I noticed this issue in Neovim 0.3.8, but after upgrading to Neovim 0.4.4, I can no longer reproduce it. Let me know if upgrading helps or if you can narrow down on the source of the issue

**Comment by qxxxb** [comment] 2020-10-13 19:16
For now, my best guess at a solution is to disable searchhi autocommands if you don't need to use them.
```vim
let g:searchhi_user_autocmds_enabled = 0
```

**Comment by roachsinai** [comment] 2020-10-14 01:20
Thanks for reply, maybe the reason is I'm using Vim?

**Comment by qxxxb** [comment] 2020-10-14 05:43
I tested on Vim 8.0 and it seems to be resolved by ensuring that `g:searchhi_user_autocmds_enabled` is set to 0, which should be its default value

**Closed by qxxxb** 2020-10-14 05:43 UTC
